---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: flatcreative
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flatcreative
  labels:
    app: flatcreative
spec:
  replicas: 1
  template:
    metadata:
      name: flatcreative
      labels:
        app: flatcreative
    spec:
      containers:
        - name: flatcreative
          image: itzg/minecraft-bedrock-server
          imagePullPolicy: Always
          env:
            - name: EULA
              value: "TRUE"
            - name: GAMEMODE
              value: creative
            - name: DIFFICULTY
              value: normal
            - name: LEVEL_TYPE
              value: flat
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bds
  selector:
    matchLabels:
      app: bds
---
apiVersion: v1
kind: Service
metadata:
  name: flatcreative
spec:
  selector:
    app: flatcreative
  ports:
    - port: 19132
      protocol: UDP
  type: LoadBalancer
